export default {
    AED: { name: 'Emirati Dirham', symbol: 'د.إ' },
    AFN: { name: 'Afghan Afghani', symbol: '؋' },
    ALL: { name: 'Albanian Lek', symbol: 'Lek' },
    AMD: { name: 'Armenian Dram', symbol: 'Դ' },
    ANG: { name: 'Dutch Guilder', symbol: 'ƒ' },
    AOA: { name: 'Angolan Kwanza', symbol: 'Kz' },
    ARS: { name: 'Argentine Peso', symbol: '$' },
    AUD: { name: 'Australian Dollar', symbol: '$' },
    AWG: { name: 'Aruban or Dutch Guilder', symbol: 'ƒ' },
    AZN: { name: 'Azerbaijan Manat', symbol: '₼' },
    BAM: { name: 'Bosnian Convertible Mark', symbol: 'KM' },
    BBD: { name: 'Barbadian or Bajan Dollar', symbol: '$' },
    BDT: { name: 'Bangladeshi Taka', symbol: 'Tk' },
    BGN: { name: 'Bulgarian Lev', symbol: 'лв' },
    BHD: { name: 'Bahraini Dinar', symbol: 'BD' },
    BIF: { name: 'Burundian Franc', symbol: 'Franc' },
    BMD: { name: 'Bermudian Dollar', symbol: '$' },
    BND: { name: 'Brunei Dollar', symbol: '$' },
    BOB: { name: 'Bolivian Bolíviano', symbol: '$b' },
    BRL: { name: 'Brazilian Real', symbol: 'R$' },
    BSD: { name: 'Bahamian Dollar', symbol: '$' },
    BTN: { name: 'Bhutanese Ngultrum', symbol: 'Ngultrum' },
    BWP: { name: 'Botswana Pula', symbol: 'P' },
    BYN: { name: 'Belarusian Ruble', symbol: 'Br' },
    BZD: { name: 'Belizean Dollar', symbol: 'BZ$' },
    CAD: { name: 'Canadian Dollar', symbol: '$' },
    CDF: { name: 'Congolese Franc', symbol: 'Franc' },
    CHF: { name: 'Swiss Franc', symbol: 'CHF' },
    CLP: { name: 'Chilean Peso', symbol: '$' },
    CNY: { name: 'Chinese Yuan Renminbi', symbol: '¥' },
    COP: { name: 'Colombian Peso', symbol: '$' },
    CRC: { name: 'Costa Rican Colon', symbol: '₡' },
    CUC: { name: 'Cuban Convertible Peso', symbol: 'CUC$' },
    CUP: { name: 'Cuban Peso', symbol: '₱' },
    CVE: { name: 'Cape Verde Escudo', symbol: '$' },
    CZK: { name: 'Czech Koruna', symbol: 'Kč' },
    DJF: { name: 'Djiboutian Franc', symbol: 'Franc' },
    DKK: { name: 'Danish Krone', symbol: 'kr' },
    DOP: { name: 'Dominican Peso', symbol: 'RD$' },
    DZD: { name: 'Algerian Dinar', symbol: 'DA' },
    EGP: { name: 'Egyptian Pound', symbol: '£' },
    ERN: { name: 'Eritrean Nakfa', symbol: 'Nkf' },
    ETB: { name: 'Ethiopian Birr', symbol: 'Br' },
    EUR: { name: 'Euro', symbol: '€' },
    FJD: { name: 'Fijian Dollar', symbol: '$' },
    FKP: { name: 'Falkland Island Pound', symbol: '£' },
    GBP: { name: 'British Pound', symbol: '£' },
    GEL: { name: 'Georgian Lari', symbol: 'Lari' },
    GGP: { name: 'Guernsey Pound', symbol: '£' },
    GHS: { name: 'Ghanaian Cedi', symbol: 'GH¢' },
    GIP: { name: 'Gibraltar Pound', symbol: '£' },
    GMD: { name: 'Gambian Dalasi', symbol: 'Dalasi' },
    GNF: { name: 'Guinean Franc', symbol: 'Franc' },
    GTQ: { name: 'Guatemalan Quetzal', symbol: 'Q' },
    GYD: { name: 'Guyanese Dollar', symbol: '$' },
    HKD: { name: 'Hong Kong Dollar', symbol: 'HK$' },
    HNL: { name: 'Honduran Lempira', symbol: 'L' },
    HRK: { name: 'Croatian Kuna', symbol: 'kn' },
    HTG: { name: 'Haitian Gourde', symbol: 'G' },
    HUF: { name: 'Hungarian Forint', symbol: 'Ft' },
    IDR: { name: 'Indonesian Rupiah', symbol: 'Rp' },
    ILS: { name: 'Israeli Shekel', symbol: '₪' },
    IMP: { name: 'Isle of Man Pound', symbol: '£' },
    INR: { name: 'Indian Rupee', symbol: '₹' },
    IQD: { name: 'Iraqi Dinar', symbol: 'د.ع' },
    IRR: { name: 'Iranian Rial', symbol: '﷼' },
    ISK: { name: 'Icelandic Krona', symbol: 'kr' },
    JEP: { name: 'Jersey Pound', symbol: '£' },
    JMD: { name: 'Jamaican Dollar', symbol: 'J$' },
    JOD: { name: 'Jordanian Dinar', symbol: 'Dinar' },
    JPY: { name: 'Japanese Yen', symbol: '¥' },
    KES: { name: 'Kenyan Shilling', symbol: 'KSh' },
    KGS: { name: 'Kyrgyzstani Som', symbol: 'лв' },
    KHR: { name: 'Cambodian Riel', symbol: '៛' },
    KMF: { name: 'Comorian Franc', symbol: 'Franc' },
    KPW: { name: 'North Korean Won', symbol: '₩' },
    KRW: { name: 'South Korean Won', symbol: '₩' },
    KWD: { name: 'Kuwaiti Dinar', symbol: 'ك' },
    KYD: { name: 'Caymanian Dollar', symbol: '$' },
    KZT: { name: 'Kazakhstani Tenge', symbol: '₸' },
    LAK: { name: 'Lao Kip', symbol: '₭' },
    LBP: { name: 'Lebanese Pound', symbol: 'ل.ل' },
    LKR: { name: 'Sri Lanka Rupee', symbol: '₨' },
    LRD: { name: 'Liberian Dollar', symbol: '$' },
    LSL: { name: 'Basotho Loti', symbol: 'Loti' },
    LYD: { name: 'Libyan Dinar', symbol: 'LD' },
    MAD: { name: 'Moroccan Dirham', symbol: 'Dirham' },
    MDL: { name: 'Moldovan Leu', symbol: 'Leu' },
    MGA: { name: 'Malagasy Ariary', symbol: 'Ar' },
    MKD: { name: 'Macedonian Denar', symbol: 'ден' },
    MMK: { name: 'Burmese Kyat', symbol: 'K' },
    MNT: { name: 'Mongolian Tughrik', symbol: '₮' },
    MOP: { name: 'Macau Pataca', symbol: 'MOP$' },
    MRU: { name: 'Mauritanian Ouguiya', symbol: 'UM' },
    MUR: { name: 'Mauritian Rupee', symbol: '₨' },
    MVR: { name: 'Maldivian Rufiyaa', symbol: 'Rufiyaa' },
    MWK: { name: 'Malawian Kwacha', symbol: 'MK' },
    MXN: { name: 'Mexican Peso', symbol: '$' },
    MYR: { name: 'Malaysian Ringgit', symbol: 'RM' },
    MZN: { name: 'Mozambican Metical', symbol: 'MT' },
    NAD: { name: 'Namibia Dollar', symbol: '$' },
    NGN: { name: 'Nigerian Naira', symbol: '₦' },
    NIO: { name: 'Nicaraguan Cordoba', symbol: 'C$' },
    NOK: { name: 'Norwegian Krone', symbol: 'kr' },
    NPR: { name: 'Nepalese Rupee', symbol: '₨' },
    NZD: { name: 'New Zealand Dollar', symbol: '$' },
    OMR: { name: 'Omani Rial', symbol: '﷼' },
    PAB: { name: 'Panamanian Balboa', symbol: 'B/.' },
    PEN: { name: 'Peruvian Sol', symbol: 'S/.' },
    PGK: { name: 'Papua New Guinean Kina', symbol: 'K' },
    PHP: { name: 'Philippine Peso', symbol: '₱' },
    PKR: { name: 'Pakistani Rupee', symbol: '₨' },
    PLN: { name: 'Polish Zloty', symbol: 'zł' },
    PYG: { name: 'Paraguayan Guarani', symbol: 'Gs' },
    QAR: { name: 'Qatari Riyal', symbol: '﷼' },
    RON: { name: 'Romanian Leu', symbol: 'lei' },
    RSD: { name: 'Serbian Dinar', symbol: 'РСД' },
    RUB: { name: 'Russian Ruble', symbol: '₽' },
    RWF: { name: 'Rwandan Franc', symbol: 'Franc' },
    SAR: { name: 'Saudi Arabian Riyal', symbol: '﷼' },
    SBD: { name: 'Solomon Islander Dollar', symbol: '$' },
    SCR: { name: 'Seychellois Rupee', symbol: '₨' },
    SDG: { name: 'Sudanese Pound', symbol: 'Pound' },
    SEK: { name: 'Swedish Krona', symbol: 'kr' },
    SGD: { name: 'Singapore Dollar', symbol: '$' },
    SHP: { name: 'Saint Helenian Pound', symbol: '£' },
    SLL: { name: 'Sierra Leonean Leone', symbol: 'c' },
    SOS: { name: 'Somali Shilling', symbol: 'S' },
    SRD: { name: 'Surinamese Dollar', symbol: '$' },
    STN: { name: 'Sao Tomean Dobra', symbol: 'Db' },
    SYP: { name: 'Syrian Pound', symbol: '£' },
    SZL: { name: 'Swazi Lilangeni', symbol: 'Lilangeni' },
    THB: { name: 'Thai Baht', symbol: '฿' },
    TJS: { name: 'Tajikistani Somoni', symbol: 'Somoni' },
    TMT: { name: 'Turkmenistani Manat', symbol: 'Manat' },
    TND: { name: 'Tunisian Dinar', symbol: 'Dinar' },
    TOP: { name: "Tongan Pa'anga", symbol: 'T$' },
    TRY: { name: 'Turkish Lira', symbol: 'TL' },
    TTD: { name: 'Trinidadian Dollar', symbol: '$' },
    TWD: { name: 'Taiwan New Dollar', symbol: 'NT$' },
    TZS: { name: 'Tanzanian Shilling', symbol: 'Shilling' },
    UAH: { name: 'Ukrainian Hryvnia', symbol: '₴' },
    UGX: { name: 'Ugandan Shilling', symbol: 'UGX' },
    USD: { name: 'US Dollar', symbol: '$' },
    UYU: { name: 'Uruguayan Peso', symbol: '$U' },
    UZS: { name: 'Uzbekistani Som', symbol: 'лв' },
    VES: { name: 'Venezuelan Bolívar', symbol: 'Bs. S' },
    VND: { name: 'Vietnamese Dong', symbol: '₫' },
    VUV: { name: 'Ni-Vanuatu Vatu', symbol: 'VT' },
    WST: { name: 'Samoan Tala', symbol: '$' },
    XAF: { name: 'Central African CFA Franc BEAC', symbol: 'CFA Franc BEAC' },
    XAG: { name: 'Silver Ounce', symbol: 'Ounce' },
    XAU: { name: 'Gold Ounce', symbol: 'Ounce' },
    XCD: { name: 'East Caribbean Dollar', symbol: '$' },
    XDR: {
        name: 'IMF Special Drawing Rights',
        symbol: 'Special Drawing Rights',
    },
    XOF: { name: 'CFA Franc', symbol: 'Franc' },
    XPD: { name: 'Palladium Ounce', symbol: 'Ounce' },
    XPF: { name: 'CFP Franc', symbol: 'Franc' },
    XPT: { name: 'Platinum Ounce', symbol: 'Ounce' },
    YER: { name: 'Yemeni Rial', symbol: '﷼' },
    ZAR: { name: 'South African Rand', symbol: 'R' },
    ZMW: { name: 'Zambian Kwacha', symbol: 'ZK' },
    ZWL: { name: 'Zimbabwe Dollar', symbol: '$' },
};
